### ISSUE TITLE
How to define errors on input fields

### ISSUE THREAD

**Issue by datalek** [casualteam/open-api-generator#2]
We need a good structure that allows us to express any error that can happen to the input fields. I found the following main errors:
* Missing parameter
* Parsing error / invalid value

## Proposal
```scala
  case class FieldError(
    name: String,
    message: String,
    location: Locations // Header | Path | Body | Query
    errorType: ErrorTypes // MissingValue | InvalidValue
  )
```
Given the above error structure, we can express errors in the following ways:
```scala
// express a missing header field:
FieldError(
   name = "Authorization",
   message = "The header field `Authorization` is missing.",
   location = Locations.Header,
   errorType = ErrorTypes.MissingValue
)
// express a badly formatted field
// (e.g. an integer is required but the provided value has a different type)
FieldError(
   name = "user.id",
   message = "The body field `user.id` has a bad format, the provided value \"xxx\" cannot be parsed to `integer` type.",
   location = Locations.Body,
   errorType = ErrorTypes.InvalidValue
)
```

**Comment by hizumisen** [comment]
I like this model but I do not know if we are able to fill `errorType` property, maybe we should just avoid error typing and only rely on the message.
Moreover in the message I was thinking of writing only the error ie. "value is not a string" instead of "the field `user.id` is not a string", since we have name and location properties.

**Comment by datalek** [comment]
The `errorType` is useful if the user (who uses this code generator) needs to customize the response based on the type of the error, and moreover it is useful to produce a human-readable error message. We can add the property`errorType` in the future *if it is useful and feasible in the real world*.

The property `message` can be dropped out or changed.

What I think we will really need, is a function that transforms a `FieldError` in something that could be used "as is" to provide human-readable information about the error, it will be really useful. But, like the property `errorType`, we can provide this function `FieldError -> HumanReadableMessage` in the future *if it is useful and feasible in the real world*.

So what do you think to simplify the solution as follows:
```scala
case class FieldError(
    name: String,
    location: Locations // Header | Path | Body | Query
  )
```

**Comment by hizumisen** [comment]
I tried to implement the first solution now and I have found these issues:
- it is easier to split the error location (name + location fields) and the actual error
- typing error can be difficult also because use circe as json decoder and we must wrap our error in his DecodingFailure which only takes a (message:String) as parameter
- a string can be more general but it is difficult to distinguish different error types

maybe we can try this

```scala
case class FieldError(
  name: String,
  location: Location,
  error: ErrorType // MissingField | InvalidField
)

object FieldError {
  def prettyPrint(error: FieldError): String = ???
}
```

**Comment by hizumisen** [comment]
I have made some changes to add this error model https://github.com/casualteam/open-api-generator/tree/feature/error-model-refactor

**Comment by datalek** [comment]
I see that, nice work!

**Comment by hizumisen** [comment]
Hi, I completed my implementation of the error model.
I had some issues when handling complex parameters (query, header, path) and I gave up on them, for example the validation on this query param is not handled
```
- in: query
  name: arrayWithStringMinMax
  schema:
    type: array
    items:
      type: string
      minLength: 1
      maxLength: 20
```

We can add handling of these constraints as future improvement.
Another limit is that error accumulation is not supported.

**Comment by datalek** [comment]
I think that it is a great start! I have only one improvement to do; We have to return a `List[FieldError]` instead of a single `FiledError`, though for now, we don't accumulate the errors.
